name: CI

on:
  pull_request:
    branches: ["*"]
  workflow_dispatch:

env:
  ACT: false

permissions:
  contents: read

jobs:
  lint-backend:
    name: Lint Backend Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8
        run: flake8 backend
